#!/bin/bash

if [[ $# -lt 1 ]]; then 
	echo "objc-run usage: objc-run file.m [params]" 1>&2
	exit 1
fi

filepath="$1"
filename="$(basename "$filepath")"
appname="${filename%.*}"
target="$(dirname "$filepath")/$appname"
shift

# check if there's already a file with the same name as our compiled app, if so exit
if [[ -f "$target" ]]; then
	echo "objc-run: file already exists at $dirname/$appname ... exiting" 1>&2
	exit 1
fi

# compile the file
# remove shebangs on first line, first chars only
clang -o "$target" -Wall -std=c99 -framework Foundation -lobjc -fobjc-arc -fmodules -x objective-c <(awk 'NR>1 || !/^#!/' "$filepath")
clangExitCode=$?

# on clang success, run compiled application and remove it
if [[ $clangExitCode -eq 0 ]]; then 
	"$target" "$@"
	rm -f "$target"
else
	echo "objc-run usage: clang returned with error" 1>&2
	exit 1
fi

# exit explicitly with no error
exit 0
